### ISSUE TITLE
null reference exception when rendering custom region

### ISSUE THREAD

**Issue by ksahmed** [PiranhaCMS/piranha.core#1121]
so i tried my own pagetype with a region .. i works ok in manager.  i created an action for it  in cms controller. but in the view , it displays null reference exception when i call displayfor 
   at Piranha.Extend.Fields.SimpleField`1.GetHashCode()
   at System.Collections.Generic.ObjectEqualityComparer`1.GetHashCode(T obj)
   at System.Collections.Generic.HashSet`1.InternalGetHashCode(T item)
   at System.Collections.Generic.HashSet`1.Contains(T item)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.TemplateInfo.Visited(ModelExplorer modelExplorer)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.TemplateBuilder.Build()
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.GenerateDisplay(ModelExplorer modelExplorer, String htmlFieldName, String templateName, Object additionalViewData)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper`1.DisplayFor[TResult](Expression`1 expression, String templateName, String htmlFieldName, Object additionalViewData)
   at Microsoft.AspNetCore.Mvc.Rendering.HtmlHelperDisplayExtensions.DisplayFor[TModel,TResult](IHtmlHelper`1 htmlHelper, Expression`1 expression)

region class is below

 public class ContactUsRegion
    {
        [Field(Title = "Please enter your name")]
        public StringField Name { get; set; }

        [Field(Title = "Please enter your email")]
        public StringField Email { get; set; }

        [Field(Title = "Please enter your Message")]
        public TextField Message { get; set; }
    }

 [PageType(Title = "Contact page", UseBlocks = false)]
    [PageTypeRoute(Title = "Default", Route = "/contact-us")]
    public class ContactPage : Page<ContactPage>
    {
        [Region(Title = "Contact us form")]
        public ContactUsRegion ContactUs { get; set; }
    }

in my custom display templte , with contactusregion as model, 

@model ContactUsRegion

@Html.DisplayFor(m => m.Name) ---> exception is generated here 
@Html.DisplayFor(m => m.Email)

@Html.DisplayFor(m => m.Message)

**Comment by tidyui** [comment]
The templates doesn’t contain any DisplayTemplates for fields as they are very simple. By calling DisplayFor on the fields you trigger the default behavior in MVC which will try to iterate all of the properties in the fields and display them. Instead, do:

    @Model.Name

And it will print the name as a string

**Comment by ksahmed** [comment]
i am not sure if i undersstand fully. 
i want to render the region which has 3 fields .. 
and what you suggested is to use @model.name instead of @html.displayfor .. am i right?  

i tried it  and 
  @Model.ContactUs.Name is not rendering anything on contact us page.. in manage i can see 3  text fields being rendered correctly 

this is my page markup 
@model ContactPage

@{
    ViewBag.Title = Model.Title;
}

<div class="main">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-10 ">
                @Model.ContactUs.Name
            </div>
        </div>
    </div>
</div>

**Comment by ksahmed** [comment]
ah i am doing it wrong. i want to display a form in contact us page and i misunderstood regions .. what a pity.. i think i will have to manually generate the form.. thank you
