### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by net4u** [PiranhaCMS/piranha.core#1157]
Hi,

I don't know if is the proper place to ask, but: after successfully run the RazorWeb example from Visual Studio, after publishing on an IIS server (where I have another .core web apps that works), the app crash and I have "HTTP Error 500.30 - ANCM In-Process Start Failure"
Any hints?

**Comment by tidyui** [comment]
@filipjansson Have you seen this error before?

**Comment by net4u** [comment]
In fact, immediately after publishing on IIS server. I can always come back to Visual Studio, and it works, but then when I publish and run from the IIS, it throw the error. 
I suppose that it seed again when it runs on IIS server.
Bellow the 3 events logged on Windows Logs->Application on the Win 2K12 server
`###########################################################################
#Event 1 (as Warning)
###########################################################################

Log Name:      Application
Source:        .NET Runtime
Date:          5/11/2020 3:42:42 PM
Event ID:      1000
Task Category: None
Level:         Warning
Keywords:      Classic
User:          N/A
Computer:      webcenter.org.infosystems4u.ro
Description:
Category: Microsoft.EntityFrameworkCore.Model.Validation
EventId: 20601

The 'bool' property 'EnableComments' on entity type 'Post' is configured with a database-generated default. This default will always be used for inserts when the property has the value 'false', since this is the CLR default for the 'bool' type. Consider using the nullable 'bool?' type instead so that the default will only be used for inserts when the property value is 'null'.

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>3</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-05-11T12:42:42.000000000Z" />
    <EventRecordID>250913</EventRecordID>
    <Channel>Application</Channel>
    <Computer>webcenter.org.infosystems4u.ro</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Category: Microsoft.EntityFrameworkCore.Model.Validation
EventId: 20601

The 'bool' property 'EnableComments' on entity type 'Post' is configured with a database-generated default. This default will always be used for inserts when the property has the value 'false', since this is the CLR default for the 'bool' type. Consider using the nullable 'bool?' type instead so that the default will only be used for inserts when the property value is 'null'.
</Data>
  </EventData>
</Event>

###########################################################################
#Event 2 (as Error)
###########################################################################

Log Name:      Application
Source:        .NET Runtime
Date:          5/11/2020 3:42:44 PM
Event ID:      1000
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      webcenter.org.infosystems4u.ro
Description:
Category: Microsoft.AspNetCore.Hosting.Diagnostics
EventId: 6

Application startup exception

Exception: 
System.ComponentModel.DataAnnotations.ValidationException: The InternalId field must be unique
   at Piranha.Services.SiteService.SaveAsync(Site model) in F:\Websites\Sources\piranha.core-master\piranha.core-master\core\Piranha\Services\SiteService.cs:line 283
   at MvcWeb.Seed.RunAsync(IApi api) in F:\Websites\Sources\piranha.core-master\piranha.core-master\examples\MvcWeb\Seed.cs:line 48
   at MvcWeb.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, IApi api) in F:\Websites\Sources\piranha.core-master\piranha.core-master\examples\MvcWeb\Startup.cs:line 124
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Server.IIS.Core.IISServerSetupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-05-11T12:42:44.000000000Z" />
    <EventRecordID>250914</EventRecordID>
    <Channel>Application</Channel>
    <Computer>webcenter.org.infosystems4u.ro</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Category: Microsoft.AspNetCore.Hosting.Diagnostics
EventId: 6

Application startup exception

Exception: 
System.ComponentModel.DataAnnotations.ValidationException: The InternalId field must be unique
   at Piranha.Services.SiteService.SaveAsync(Site model) in F:\Websites\Sources\piranha.core-master\piranha.core-master\core\Piranha\Services\SiteService.cs:line 283
   at MvcWeb.Seed.RunAsync(IApi api) in F:\Websites\Sources\piranha.core-master\piranha.core-master\examples\MvcWeb\Seed.cs:line 48
   at MvcWeb.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, IApi api) in F:\Websites\Sources\piranha.core-master\piranha.core-master\examples\MvcWeb\Startup.cs:line 124
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.&lt;&gt;c__DisplayClass4_0.&lt;Build&gt;b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.&lt;&gt;c__DisplayClass13_0.&lt;UseStartup&gt;b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.&lt;&gt;c__DisplayClass0_0.&lt;Configure&gt;g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Server.IIS.Core.IISServerSetupFilter.&lt;&gt;c__DisplayClass2_0.&lt;Configure&gt;b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.&lt;&gt;c__DisplayClass0_0.&lt;Configure&gt;b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
</Data>
  </EventData>
</Event>

###########################################################################
#Event 3 (as Error)
###########################################################################

Log Name:      Application
Source:        .NET Runtime
Date:          5/11/2020 3:42:44 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      webcenter.org.infosystems4u.ro
Description:
Application: w3wp.exe
CoreCLR Version: 4.700.20.11803
.NET Core Version: 3.1.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ComponentModel.DataAnnotations.ValidationException: The InternalId field must be unique
   at Piranha.Services.SiteService.SaveAsync(Site model) in F:\Websites\Sources\piranha.core-master\piranha.core-master\core\Piranha\Services\SiteService.cs:line 283
   at MvcWeb.Seed.RunAsync(IApi api) in F:\Websites\Sources\piranha.core-master\piranha.core-master\examples\MvcWeb\Seed.cs:line 48
   at MvcWeb.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, IApi api) in F:\Websites\Sources\piranha.core-master\piranha.core-master\examples\MvcWeb\Startup.cs:line 124
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Server.IIS.Core.IISServerSetupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at MvcWeb.Program.Main(String[] args) in F:\Websites\Sources\piranha.core-master\piranha.core-master\examples\MvcWeb\Program.cs:line 21

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-05-11T12:42:44.000000000Z" />
    <EventRecordID>250915</EventRecordID>
    <Channel>Application</Channel>
    <Computer>webcenter.org.infosystems4u.ro</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: w3wp.exe
CoreCLR Version: 4.700.20.11803
.NET Core Version: 3.1.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ComponentModel.DataAnnotations.ValidationException: The InternalId field must be unique
   at Piranha.Services.SiteService.SaveAsync(Site model) in F:\Websites\Sources\piranha.core-master\piranha.core-master\core\Piranha\Services\SiteService.cs:line 283
   at MvcWeb.Seed.RunAsync(IApi api) in F:\Websites\Sources\piranha.core-master\piranha.core-master\examples\MvcWeb\Seed.cs:line 48
   at MvcWeb.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, IApi api) in F:\Websites\Sources\piranha.core-master\piranha.core-master\examples\MvcWeb\Startup.cs:line 124
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.&lt;&gt;c__DisplayClass4_0.&lt;Build&gt;b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.&lt;&gt;c__DisplayClass13_0.&lt;UseStartup&gt;b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.&lt;&gt;c__DisplayClass0_0.&lt;Configure&gt;g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Server.IIS.Core.IISServerSetupFilter.&lt;&gt;c__DisplayClass2_0.&lt;Configure&gt;b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.&lt;&gt;c__DisplayClass0_0.&lt;Configure&gt;b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at MvcWeb.Program.Main(String[] args) in F:\Websites\Sources\piranha.core-master\piranha.core-master\examples\MvcWeb\Program.cs:line 21
</Data>
  </EventData>
</Event>
`

**Comment by tidyui** [comment]
The first "error" is a migration warning that we didn't see during development. But like you say, the second error `The InternalId field must be unique` seems to be related to the fact that it's trying to insert the same data twice into the database.

**Comment by net4u** [comment]
I have no idea how to get rid about this.
Is not a flag anywhere about the status of migration? A kind of "IsInstalled" Boolean, maybe in settings?

**Comment by net4u** [comment]
Also, error #2 at first sight is about failing to copy some *.jpg/png files from "seed" folder, that in fact does not exist after publishing operation.

**Comment by tidyui** [comment]
So I missed one issue in your initial statement. You say that you published the `RazorWeb` project that is one of the example projects in the repo, I misread and thought you had created a new project from the razor blog template `dotnet new piranha.blog.razor`.

The RazorWeb project **always** performs a data seed on start, and like you say the seed data is not copied when publishing the project. The reason for this is simply because the project is not intended to be published, it's simply a test project for development.

If you want to publish this project as a test I suggest you include the seed data in the `csproj` to make sure it's copied to the output folder on publish, otherwise it will fail.

However, if you're starting a new project we strongly encourage you to use one of our project templates that can be found here:

https://www.nuget.org/packages/Piranha.Templates/

Best regards

**Comment by net4u** [comment]
Hi, I have some succes following this approach, but still the behave is not how I expect: I build project, run from VS, it seed, maybe I play arround, I add some page etc. Then I publish on IIS, it start without error(s), but still the first step is to seed again. So if my db came with some data (as I say, when I run from VS, I add some pages), all is overwriten.  Btw, I think that adding Templates via vsix may be preferable.  For me, with "dotnet new -i Piranha.Templates" results are not really ok. It's clear that I have the template(s), but nothing is available in VS2019 when I choose "Create New Project". Or maybe I have some issues also with this.

**Comment by goranhell** [comment]
I've used dotnet new for Piranha templates several times. Never any problems

**Comment by tidyui** [comment]
@net4u `dotnet new piranha...` creates a project that uses `SQLite` for the database as this is the fastest way to get started. As the database is file-based, make sure that the database file is included in the publish because if it isn't Piranha will seed a new database. 

However, as we don't recommend using `SQLite` for production scenarios I'd say that in 99% of all cases people start projects with `SQLite` just to get up and running, then they quickly change to `SQLServer`, `MySql` or `PostgreSQL` which isn't file based.

As for building Visual Studio templates we've looked into this in the past, and there are some pitfalls to it.

1. It's not cross-platform and only supports VS
2. The new templating system in .NET Core doesn't support Visual Studio Templates, but Microsoft has sneaked around this (see below).
3. If we provided Visual Studio Templates they would be dependent on you installing another set of templates as well, and user support would never end for us (see below).

### About templates for .NET Core

To clarify. All of the .NET Core project-, or file templates you have in VS actually executes a template that works just like ours behind the scenes (`dotnet new`). This is easy for MS to implement as downloading VS also downloads the .NET Core SDK, and the SDK includes their templates. 

For us it's not as simple. We would first have to provide the templates we already have. Then we would have to build Visual Studio templates that are just "wrappers" executing the `dotnet new` templates. We have no option to force install the CLI templates when the VS templates are installed, so it all comes down to writing instructions that you need to install another set of templates **as well** for the VS Templates to work.

All in all, it's a crap solution not intended for third party providers like us, and the effort and support it would take us to do it is by no means equivalent to the gains it would give.

Best regards

**Comment by tidyui** [comment]
For the next version our templates will have options for creating the projects for a given configuration, for example:

    dotnet new piranha.web.razor -d SQLServer -s BlobStorage

would create a new web application for Razor Pages with providers for SqlServer and Azure BlobStorage. Hopefully this will make it easier to generate everything you need out of the box.

Best regards

**Comment by net4u** [comment]
I will aways prefer MS SQL. I will investigate how to change the provider to MSSQl.
For now I have:
`// Service setup
            services.AddPiranha(options =>
            {
                options.UseFileStorage();
                options.UseImageSharp();
                options.UseManager();
                options.UseTinyMCE();
                options.UseMemoryCache();
                //options.UseSqlServer(Configuration.GetConnectionString("mydb"));
                options.UseEF<SQLiteDb>(db =>
                    db.UseSqlite(Configuration.GetConnectionString("piranha")));
                options.UseIdentityWithSeed<IdentitySQLiteDb>(db =>
                    db.UseSqlite(Configuration.GetConnectionString("piranha")));
            });`

What should go, and what to remain?

**Comment by tidyui** [comment]
@net4u You can find this information in the Docs:

https://piranhacms.org/docs/architecture/databases/sql-server
https://piranhacms.org/docs/architecture/authentication/identity

Regards
