### ISSUE TITLE
Cant't remove an archive that contains posts

### ISSUE THREAD

**Issue by AndBlo** [PiranhaCMS/piranha.core#1252]
Hey!
First of all I would like to say that I love working with Piranha. It's so nice to be able to have full control of the functionality without the framework being intrusive. So good job!

So the issue I've noticed is this: If I try to remove an archive that has containing posts I get an error. I first have to delete all posts in said archive before deleting the archive to succeed. I don't know if this is by design, if so a more helpful message would be nice.
I understand this is not the most common use case, but it would be helpful in the development process to be able to delete an entire archive without removing the posts first.

Cheers!

**Comment by tidyui** [comment]
Hi there! What database are you using and do you have a more detailed error message. The foreign key relationship to the page is set to `CASCADE` on delete so it should work they way you expected it to:

https://github.com/PiranhaCMS/piranha.core/blob/master/data/Piranha.Data.EF.SQLServer/Migrations/20171215130248_AddBlogging.cs#L104

Regards

**Comment by AndBlo** [comment]
I'm using a mariadb database with the mysql-connector. It seems to be related to the relationship between posts and categories
Here is the stack trace (dbname is masked with ************* ):
```
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Cannot delete or update a parent row: a foreign key constraint fails (`*************`.`piranha_posts`, CONSTRAINT `FK_Piranha_Posts_Piranha_Categories_CategoryId` FOREIGN KEY (`CategoryId`) REFERENCES `piranha_categories` (`Id`))
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Cannot delete or update a parent row: a foreign key constraint fails (`*************`.`piranha_posts`, CONSTRAINT `FK_Piranha_Posts_Piranha_Categories_CategoryId` FOREIGN KEY (`CategoryId`) REFERENCES `piranha_categories` (`Id`))
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 775
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 49
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 116
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 391
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\CommandExecutor.cs:line 62
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
```

**Comment by tidyui** [comment]
Well categories also have a foreign key to Page with cascade delete **AND** posts have a foreign key to category. However it seems weird that the database is unable to resolve in which order it should perform the cascade deletes to not run into these kinds of issues.

However I have no previous experience in MariaDb and what it is capable of.

**Comment by AndBlo** [comment]
Maybe there is something that doesn't completely match, or a bug, in the MySql-provider for EF Core when using MariaDb. However, it's not a big problem really. I haven't noticed any similar problems anywhere else.

Thanks!

**Comment by tidyui** [comment]
As we don't currently have MariaDB as a supported database I will close this issue. It would however be interesting to open an issue describing the general issue either on MariaDB to see what they say about it when using the `MySql` connector.
