### ISSUE TITLE
Media Manager thumb error with no ImageProcessor

### ISSUE THREAD

**Issue by i-love-code** [PiranhaCMS/piranha.core#1288]
I may be doing something wrong here.

Root Issue: Media thumbnails aren't working in the manager
![image](https://user-images.githubusercontent.com/1737733/89150546-68158080-d524-11ea-8cf1-0f7380d0f8e7.png)

It's a bit odd, because they work _everywhere_ else. When I upload it, I see a thumbnail that it was uploaded successfully with the image. I can click the media to see the details and I see the media preview _and_ the "get public URL" link works.

Only the thumbnail on the larger media manager page is broken.

Video of issue: https://i.gyazo.com/b794420cf553e729f9ca692ccb96d7b3.mp4

**Using:**
```
<PackageReference Include="Piranha.AspNetCore" Version="8.3.0" />
<PackageReference Include="Piranha.AspNetCore.Identity" Version="8.3.0" />
<PackageReference Include="Piranha.AspNetCore.Identity.SQLite" Version="8.3.0" />
<PackageReference Include="Piranha.AttributeBuilder" Version="8.3.0" />
<PackageReference Include="Piranha.Data.EF" Version="8.3.0" />
<PackageReference Include="Piranha.Data.EF.SQLite" Version="8.3.0" />
<PackageReference Include="Piranha.Local.FileStorage" Version="8.3.0" />
<PackageReference Include="Piranha.Manager" Version="8.3.1" />
<PackageReference Include="Piranha.Manager.TinyMCE" Version="8.3.0" />
```

**Relevant code:**
```
services.AddPiranha(options =>
{
     options.AddRazorRuntimeCompilation = true;

     options.UseFileStorage(naming: Piranha.Local.FileStorageNaming.UniqueFolderNames, basePath: "wwwroot/cms-content/", baseUrl: "~/cms-content/");
     options.UseManager();
     options.UseTinyMCE();
     options.UseMemoryCache();
     options.UseEF<SQLiteDb>(db => db.UseSqlite(configuration.GetConnectionString("CMS")));
     options.UseIdentityWithSeed<IdentitySQLiteDb>(db => db.UseSqlite(configuration.GetConnectionString("CMS")));
});
```

(The upload and path appear to match the startup)
![image](https://user-images.githubusercontent.com/1737733/89150755-e5d98c00-d524-11ea-8135-8b61de9db82e.png)

**Comment by i-love-code** [comment]
Forgot this, the 500 error:
```
System.ArgumentException: Value cannot be null or empty. (Parameter 'url')
   at Microsoft.AspNetCore.Mvc.ControllerBase.Redirect(String url)
   at Piranha.Manager.Controllers.MediaApiController.GetUrl(Guid id, Nullable`1 width, Nullable`1 height)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Piranha.AspNetCore.SitemapMiddleware.Invoke(HttpContext context, IApi api, IApplicationService service)
   at Piranha.AspNetCore.IntegratedMiddleware.Invoke(HttpContext context, IApi api, IApplicationService service)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by i-love-code** [comment]
It appears to be something within in the media controller:
```
if (media != null)
{
        return Redirect(media.PublicUrl);
}
```

I just haven't figured out yet why, only in the media manager thumbnail preview, this PublicUrl is null/empty when it generates one fine (seen in the video, it knows the public URL)

**Comment by i-love-code** [comment]
I guess you can _kinda_ call this solved? I had a hunch since the URL it was failing to resolve was /api/media<something>/210/100 that it was due to not using the ImageSharp nuget package. I installed it and added `UseImageSharp()` and it functions now.

Is there a hard dependency on ImageSharp in the manager, or can it be opted out of? If I didn't want to have image resizing/etc, I'd assume the manager would still work.

If this was documented somewhere, my apologies.

**Comment by tidyui** [comment]
There’s not supposed to be a hard dependency and the original file should be returned when there’s no processor registered **but** apparently something is not checking this the correct way.
