### ISSUE TITLE
Restart during publish - DbUpdateException

### ISSUE THREAD

**Issue by monsieurberry** [PiranhaCMS/piranha.core#1325]
Hi,

Just a quick question about an outage we just experienced. 

Still investigating matters, but what I believe to have happened is that got rebooted whilst somebody was in the middle of publishing something.

When the site came back - it was failing during startup.cs when hitting the PageTypeBuilder initializer.

The exception I received was as follows...

`Application startup exception Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.`

Inner exception, whilst possibly misleading, was 

`Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
`
We did a restore of our content DB which worked perfectly, but just wondering is there any way to recover from this other than restoring the database? 

Cheers

Adam

**Comment by monsieurberry** [comment]
Here is full stack trace actually pulled from startup log - might be handier....

`Application '/LM/W3SVC/1334671581/ROOT' with physical root 'D:\home\site\wwwroot\' hit unexpected managed exception, exception code = '0xe0434352'. First 30KB characters of captured stdout and stderr logs:
Unhandled exception. Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---&gt; Microsoft.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
 ---&gt; System.ComponentModel.Win32Exception (258): The wait operation timed out.
   at Microsoft.Data.SqlClient.SqlCommand.&lt;&gt;c.&lt;ExecuteDbDataReaderAsync&gt;b__164_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.&lt;&gt;c.&lt;.cctor&gt;b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&amp; currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:9192e0d8-5f1d-44c9-ac3e-8e26e6aaa7cd
Error Number:-2,State:0,Class:11
ClientConnectionId before routing:e0dce5e8-0042-4c87-af37-c92aee55b9eb
Routing Destination:e279c33f1993.tr642.northeurope1-a.worker.database.windows.net,11037
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Piranha.Repositories.PageTypeRepository.Save(PageType model)
   at Piranha.Services.PageTypeService.SaveAsync(PageType model)
   at Piranha.AttributeBuilder.PageTypeBuilder.BuildAsync()
   at Piranha.AttributeBuilder.ContentTypeBuilder`2.Build()
   at DigiBook.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, IApi api, IAccountService accService) in C:\Projects\DigiBook\DigiBook\Startup.cs:line 208
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.&lt;&gt;c__DisplayClass4_0.&lt;Build&gt;b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.&lt;&gt;c__DisplayClass13_0.&lt;UseStartup&gt;b__2(IApplicationBuilder app)
   at Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter.&lt;&gt;c__DisplayClass2_0.&lt;Configure&gt;b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.&lt;&gt;c__DisplayClass0_0.&lt;Configure&gt;g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Server.IIS.Core.IISServerSetupFilter.&lt;&gt;c__DisplayClass2_0.&lt;Configure&gt;b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.&lt;&gt;c__DisplayClass0_0.&lt;Configure&gt;b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at DigiBook.Program.Main(String[] args) in C:\Projects\DigiBook\DigiBook\Program.cs:line 32`

**Comment by tidyui** [comment]
Well the error messages doesn’t really indicate that anything went wrong in Piranha, all of the errors are coming from EF Core and/or SQL Server. Isn’t it possible that the connections opened by the process that got reboot was hanging in the middle of a transaction. When the application restarted it couldn’t save to the database as it was locked by the previous process. When you restored the database all connections were closed and everything went back to normal.

Again this is just a qualified guess!

**Comment by monsieurberry** [comment]
Good point! 

In which case would a forced restart of the database or forced closing of existing connections have worked do you think? My EF Core knowledge is pretty bad - time to buy a few books.

I don't want to try and recreate the scenario (it was fairly stressful :-D ) but good to have the information in case it ever happens again!

Thanks!

**Comment by tidyui** [comment]
This is my guess from looking at the stack trace. Piranha doesn't really have any complex transactions going on as each service has it's completely own Unit Of Work. This means that chances of data going corrupt by halting half way through a save is very small. It's much more likely that the database was hanging due to open connections/transactions.

**Comment by monsieurberry** [comment]
Cool, thanks for taking a look for me

Hopefully if it happens again i'll be able to sort it out

Cheers!
