### ISSUE TITLE
Error when referencing Microsoft.EntityFrameworkCore.SqlServer

### ISSUE THREAD

**Issue by zoinkydoink** [PiranhaCMS/piranha.core#1370]
Take this https://github.com/tidyui/piranha-backend  (change it to .NET 5) and simply add a reference to 

`<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.0-rc.2.20475.6" />`

You will get the following error, on a side note, I would also like to use v9.0 but not sure what Startup.cs is going to look like since you mentioned a lot of consolidation is done 

```
System.Exception
  HResult=0x80131500
  Message=Could not resolve a service of type 'Piranha.IApi' for the parameter 'api' of method 'Configure' on type 'PiranhaBackend.Startup'.
  Source=Microsoft.AspNetCore.Hosting
  StackTrace:
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Server.IIS.Core.IISServerSetupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.<StartAsync>d__31.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at PiranhaBackend.Program.Main(String[] args) in C:\Users\kovan\Downloads\piranha-backend-main\piranha-backend-main\Program.cs:line 16

Inner Exception 1:
TypeLoadException: Method 'Create' in type 'Microsoft.EntityFrameworkCore.Sqlite.Query.Internal.SqliteQueryableMethodTranslatingExpressionVisitorFactory' from assembly 'Microsoft.EntityFrameworkCore.Sqlite, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.

```

**Comment by tidyui** [comment]
This is not how you change database in Piranha. As migrations are database dependent you need to change packages and adjust your `Startup.cs` accordingly, otherwise you will execute the `SqLite` migrations on `SqlServer`. Take a look here for reference:

* https://piranhacms.org/docs/architecture/databases/sql-server
* https://piranhacms.org/docs/architecture/authentication/identity

**Comment by zoinkydoink** [comment]
Iam using SQL server for other things in my project, not for piranha, piranha could still use Sqlite and rest can use sql server

**Comment by tidyui** [comment]
When you add a reference to `SqlServer` from `.NET 5` all of the common dependencies for both `SqlServer` and `SqLite` will be updated. It looks like the error is caused by the common `Microsoft` packages for `.NET 5` aren't compatible with `.NetCoreApp 3.1`. 

If you want to try the `.NET 5` packages my guess is that you need to upgrade the `SqLite` packages used by `Piranha.Data.EF.SQLite` as well. Still we can't guarantee that it will work as we don't officially support `.NET 5` yet.
