### ISSUE TITLE
Exception is throwed when getting pages contains the region has only one field.

### ISSUE THREAD

**Issue by vantm** [PiranhaCMS/piranha.core#1408]
### Create page type and region type

```cs
public class Display
{
    [Field(Title = "Background image")]
    public ImageField Background { get; set; }
}

[PageType(Title = "Home page")]
public class HomePage : Page<HomePage>
{
    [Region(Title = "Display configuration")]
    public Display Display { get; set; }
}
```

### Create a controller and get pages by model

```cs
[Route("api/[controller]")]
public class PagesController : ControllerBase
{
    private readonly IApi _api;

    public PagesController(IApi api)
    {
        _api = api;
    }

    [HttpGet]
    public async Task<IActionResult> GetPages()
    {
        var pages = await _api.Pages.GetAllAsync<HomePage>();
        return Ok(pages);
    }
}
```

### Actual output

An exception is throwed as bellow:

```
System.ArgumentException: Object of type 'Piranha.Extend.Fields.ImageField' cannot be converted to type 'WebPiranha.Models.Regions.Display'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at Piranha.Services.ContentFactory.CreateModelAsync[T](ContentTypeBase type)
   at Piranha.Services.ContentService`3.TransformAsync[T](TContent content, ContentTypeBase type, Func`3 process)
   at Piranha.Repositories.PageRepository.GetById[T](Guid id)
   at Piranha.Services.PageService.GetByIdAsync[T](Guid id)
   at Piranha.Services.PageService.GetAllAsync[T](Nullable`1 siteId)
   at WebPiranha.Controllers.PagesController.GetPages() in C:\Users\vtran\source\repos\WebPiranha\Controllers\PagesController.cs:line 21
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Piranha.AspNetCore.SitemapMiddleware.Invoke(HttpContext context, IApi api, IApplicationService service)
   at Piranha.AspNetCore.IntegratedMiddleware.Invoke(HttpContext context, IApi api, IApplicationService service)
   at Piranha.AspNetCore.Security.SecurityMiddleware.InvokeAsync(HttpContext ctx, IApplicationService service)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### Expected

It should not throw any exception.

### Specification

**.NET Core 3.1**

.csproj package reference

```xml
<ItemGroup>
  <PackageReference Include="Piranha" Version="8.4.2" />
  <PackageReference Include="Piranha.AspNetCore" Version="8.4.1" />
  <PackageReference Include="Piranha.AspNetCore.Identity.SQLServer" Version="8.4.0" />
  <PackageReference Include="Piranha.AttributeBuilder" Version="8.4.0" />
  <PackageReference Include="Piranha.Data.EF.SQLServer" Version="8.4.0" />
  <PackageReference Include="Piranha.ImageSharp" Version="8.4.0" />
  <PackageReference Include="Piranha.Local.FileStorage" Version="8.4.0" />
  <PackageReference Include="Piranha.Manager" Version="8.4.1" />
  <PackageReference Include="Piranha.Manager.TinyMCE" Version="8.4.0" />
</ItemGroup>
```

**Comment by tidyui** [comment]
This is not a bug, this is due to how the model transformation works. See the documentation here under “Single Field Regions” for more information! https://piranhacms.org/docs/content/regions

**Comment by selaromdotnet** [comment]
> This is not a bug, this is due to how the model transformation works. See the documentation here under “Single Field Regions” for more information! https://piranhacms.org/docs/content/regions

would you mind sharing a quick technical summary of why this is the case? I'm writing a few blog posts about piranha, and i'm pointing out this requirement for regions/fields but while I did catch this in the docs, I wasn't clear exactly why a single field region causes issues. 

if you have a chance, would you kindly share a few details about it so I can add it to the post? thanks!
