### ISSUE TITLE
How to debug a Piranha exception? Would it be possible to include more information?

### ISSUE THREAD

**Issue by horacioj** [PiranhaCMS/piranha.core#1577]
Hi,

An example, but the question is generic, not only for this specific case.

Let's say for example you have a field like `public SelectField<Whatever>? Something { get; set; }`
Let's say there is content already created.

Let's say the field is updated to be (notice the renamed type) `public SelectField<WhateverElse>? Something { get; set; }`

Then, for example when trying to edit the page the Piranha Manager (API call) will throw a generic exception like:

```
StatusCode = 500 
OriginalPath =  
Path = /Error. 
Error Message = Object reference not set to an instance of an object.. 
Error Source = System.Private.CoreLib. 
Inner Exception = null. 
Error StackTrace =    at System.Object.GetType()
   at Piranha.Services.ContentFactory.InitFieldAsync(IServiceScope scope, Object field, Boolean managerInit)
   at Piranha.Services.ContentFactory.InitDynamicRegionAsync(IServiceScope scope, Object region, ContentTypeRegion regionType, Boolean managerInit)
   at Piranha.Services.ContentFactory.InitDynamicAsync[T](T model, ContentTypeBase type, Boolean managerInit)
   at Piranha.Services.PageService.OnLoadAsync(PageBase model, Boolean isDraft)
   at Piranha.Services.PageService.GetByIdsAsync[T](Guid[] ids)
   at Piranha.Services.PageService.GetByIdAsync[T](Guid id)
   at Piranha.Manager.Services.PageService.GetById(Guid id, Boolean useDraft)
   at Piranha.Manager.Controllers.PageApiController.Get(Guid id)
   at lambda_method1178(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at 
   ...
   ...
```
There is no clue about where the problem could be. I can only know which page has the problem (the one being loaded) but no idea about what region or filed or block or something else could be wrong.

Would it be possible to include in the exception some information that could make it easier to find what may need to be manually update in the database? 
In this case, the problem was the saved CLR Type `Whatever` doesn't exist anymore. Perhaps the exception could include the name of the CLR Type that could not be resolved?

Thanks!

**Comment by horacioj** [comment]
Perhaps add logger debug events before and after processing a region / field / block saying which thing is being processed?

**Comment by horacioj** [comment]
Another example. How can I find which is the "given field"?

```
System.ArgumentException: Given field value does not match the configured type
   at Piranha.Services.ContentService`3.MapRegion(TContent content, Object region, ContentTypeRegion regionType, String regionId, Int32 sortOrder, Nullable`1 languageId)
   at Piranha.Services.ContentService`3.Transform[T](T model, ContentTypeBase type, TContent dest, Nullable`1 languageId)
   at Piranha.Repositories.PageRepository.Save[T](T model, Boolean isDraft)
   at Piranha.Repositories.PageRepository.SaveDraft[T](T model)
   at Piranha.Services.PageService.SaveAsync[T](T model, Boolean isDraft)
   at Piranha.Manager.Services.PageService.Save(PageEditModel model, Boolean draft)
   at Piranha.Manager.Controllers.PageApiController.Save(PageEditModel model, Boolean draft)
   at Piranha.Manager.Controllers.PageApiController.SaveDraft(PageEditModel model)
   at lambda_method1161(Closure , Object )
```

**Comment by jensbrak** [comment]
Personally, if I want to dig into the workings of Piranha (for whatever reason) I replace the Nuget references with a fresh copy of the source code from here. The perks of open source in practice :)
(And I keep a copy of the relevant .csproj so that I easily can swap between nuget and project refs)

**Comment by tidyui** [comment]
@horacioj It's a good idea to add logging, at the moment we've probably just added it to the places we needed to when monitoring the flow of the requests going through the pipeline. One could also argue what we should do when a property (field) changes its type. This is not something that is supported at the moment, but one obvious solution could of course be to just discard the value totally when deserializing the model.

**Comment by horacioj** [comment]
@jensbrak, that could work on development, but what really worries me is something like this happening on production.

**Comment by jensbrak** [comment]
> @jensbrak, that could work on development, but what really worries me is something like this happening on production. 

Missed that it was production that you needed to troubleshoot, my bad.

**Comment by tidyui** [comment]
@horacioj It's impossible for these kind of errors to occur in production if you test on adequate data before pushing dev to production. The current deserialization system just doesn't support changing property values of already mapped fields, it just doesn't know what to do with the values.

Both of the errors you have provided are the same thing, i.e the serializer associated with the **stored** value doesn't match the type of the property it's being mapped against. 

This particular error is definitely something we could include in the documentation, or handle differently. The reason the system behaves the way it does is so that you won't loose data without realizing it. Let's say you have 50 pages of a certain type and you change the property value in the type. Just wiping the data isn't always the best solution either.

Regards
