### ISSUE TITLE
The type initializer for 'Piranha.Data.EF.Module' threw an exception.

### ISSUE THREAD

**Issue by hellfirehd** [PiranhaCMS/piranha.core#1858]
The following code throws a `TargetInvocationException` on startup:

```csharp
builder.AddPiranha(options =>
{
	options.AddRazorRuntimeCompilation = true;

	options.UseCms();
	options.UseManager();

	options.UseFileStorage(naming: Piranha.Local.FileStorageNaming.UniqueFolderNames);
	options.UseImageSharp();
	options.UseTinyMCE();
	options.UseMemoryCache();

	var connectionString = builder.Configuration.GetConnectionString(CpcaConsts.WebsiteDatabase);
	options.UseEF<SQLServerDb>(db => db.UseSqlServer(connectionString));
	options.UseIdentityWithSeed<IdentitySQLServerDb>(db => db.UseSqlServer(connectionString));

});
```

The exception is thrown from `options.UseEF<>()`.

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'Piranha.Data.EF.Module' threw an exception.
 ---> System.MissingMethodException: Method not found: 'Void AutoMapper.IMemberConfigurationExpression`3.Ignore()'.
   at Piranha.Data.EF.Module.<>c.<.cctor>b__16_2(IMemberConfigurationExpression`3 o)
   at AutoMapper.Configuration.MappingExpression`2.ForDestinationMember[TMember](MemberInfo destinationProperty, Action`1 memberOptions)
   at AutoMapper.Configuration.MappingExpression`2.ForMember[TMember](Expression`1 destinationMember, Action`1 memberOptions)
   at Piranha.Data.EF.Module.<>c.<.cctor>b__16_0(IMapperConfigurationExpression cfg)
   at AutoMapper.MapperConfiguration.Build(Action`1 configure)
   at AutoMapper.MapperConfiguration..ctor(Action`1 configure)
   at Piranha.Data.EF.Module..cctor()
   --- End of inner exception stack trace ---
   at Piranha.Data.EF.Module..ctor()
   at System.RuntimeType.CreateInstanceOfT()
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceOfT()
   at System.Activator.CreateInstance[T]()
   at Piranha.Runtime.AppModuleList.OnRegister[TValue](AppModule item)
   at Piranha.Runtime.AppDataList`2.Register[TValue]()
   at PiranhaEFExtensions.RegisterServices[T](IServiceCollection services, ServiceLifetime scope)
   at PiranhaEFExtensions.AddPiranhaEF[T](IServiceCollection services, Action`1 dboptions, Int32 poolSize, ServiceLifetime scope)
   at PiranhaEFExtensions.UseEF[T](PiranhaServiceBuilder serviceBuilder, Action`1 dboptions, Int32 poolSize, ServiceLifetime scope)
   at Program.<>c__DisplayClass0_0.<<Main>$>b__0(PiranhaServiceBuilder options) in D:\Source\CPCAv4\source\CPCA.Presentation.CMS\Program.cs:line 40
```

Here is my .csproj:
```xml
<ItemGroup>
	<PackageReference Include="Piranha" Version="10.0.4" />
	<PackageReference Include="Piranha.AspNetCore" Version="10.0.4" />
	<PackageReference Include="Piranha.AspNetCore.Identity.SQLServer" Version="10.0.4" />
	<PackageReference Include="Piranha.AttributeBuilder" Version="10.0.4" />
	<PackageReference Include="Piranha.Data.EF.SQLServer" Version="10.0.4" />
	<PackageReference Include="Piranha.ImageSharp" Version="10.0.4" />
	<PackageReference Include="Piranha.Local.FileStorage" Version="10.0.4" />
	<PackageReference Include="Piranha.Manager" Version="10.0.4" />
	<PackageReference Include="Piranha.Manager.LocalAuth" Version="10.0.4" />
	<PackageReference Include="Piranha.Manager.TinyMCE" Version="10.0.4" />
</ItemGroup>
```
I've checked to ensure that all my project dependencies also use AutoMapper v11.0.1.

Any thoughts?

**Comment by tidyui** [comment]
Piranha uses AutoMapper 10.1.1 (https://www.nuget.org/packages/Piranha.Data.EF/) and has not been tested on version 11, so if you’re using that version most likely they’ve made a breaking change between these majors.

Best regards

**Comment by hellfirehd** [comment]
Thanks!

I'm okay to rollback to 10.1.1 so I'll do that.
