### ISSUE TITLE
Could not resolve a service of type 'Piranha.IApi' for the parameter 'api' of method 'Configure' on type 'IRWebsiteCMS.Startup'

### ISSUE THREAD

**Issue by zakwillis** [PiranhaCMS/piranha.core#534]
Hello, I built on top of the sample .Net Core website - i.e. I modified the templates, contents, added extra page types. Running the application within Visual Studio IIS Express is fine. Running on visual studio command prompt dotnet command is fine too. 

However, I located the web.config IIS command and ran it from command line, outputting to file along the lines of this. You may notice it says .net core 2.2. So that could be a clue.

"C:\Program Files\dotnet\dotnet.exe" exec "C:\InfoRhino\cms\IRWebsite\IRWebsiteCMS\bin\Debug\netcoreapp2.2\IRWebsiteCMS.dll" > "C:\InfoRhino\cms\Testing\Output.txt"

My feeling is, the dependency resolver isn't caching the piranha API. I am normally a Ninject guy in the old .Net Framework so will have to understand more about it.

This is the configure method inside Startup.cs 

   public void Configure(IApplicationBuilder app, IHostingEnvironment env, IServiceProvider services, **IApi api)**
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

Here is some of the stack trace....

info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\zak_w\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
Application startup exception: System.Exception: Could not resolve a service of type 'Piranha.IApi' for the parameter 'api' of method 'Configure' on type 'IRWebsiteCMS.Startup'. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: connectionString
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotEmpty(String value, String parameterName)
   at Microsoft.EntityFrameworkCore.SqlServerDbContextOptionsExtensions.UseSqlServer(DbContextOptionsBuilder optionsBuilder, String connectionString, Action`1 sqlServerOptionsAction)
   at IRWebsiteCMS.Startup.<>c__DisplayClass0_0.<ConfigureServices>b__1(DbContextOptionsBuilder options) in C:\InfoRhino\cms\IRWebsite\IRWebsiteCMS\Startup.cs:line 51
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass1_0`2.<AddDbContext>b__0(IServiceProvider p, DbContextOptionsBuilder b)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.DbContextOptionsFactory[TContext](IServiceProvider applicationServiceProvider, Action`2 optionsAction)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass10_0`1.<AddCoreServices>b__0(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
      Application startup exception
System.Exception: Could not resolve a service of type 'Piranha.IApi' for the parameter 'api' of method 'Configure' on type 'IRWebsiteCMS.Startup'. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: connectionString

**Comment by w0ns88** [comment]
Are you using SQLServer? how did you setup the SQL configuration in your `Startup.cs`? To me it seems more of a db connection string issue?

**Comment by zakwillis** [comment]
I notice things about connection string. I will take a look at your project later to try and look into it.

**Comment by zakwillis** [comment]
Taking my boy to the doctor's now, so will take a look later. Thanks

**Comment by zakwillis** [comment]
Hello David, 
I went back to basics, proved the WebMVC running on SQLLITE deploys successfully to IIS. I noticed I had to set permissions on the *.db sqllite file.

I went through the documentation again and noticed the issue was with the dependency resolver.
I did as it says in the documentation. I am relatively new to .Net Core MVC. 
   public IConfiguration Configuration { get; private set; }

        public Startup(IHostingEnvironment env)
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json")
                .AddEnvironmentVariables();
            Configuration = builder.Build();
        }

I also set the following for the SQL Server connectivity. I assume this is correct.

            services.AddPiranhaEF(options =>
            options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));

            services.AddPiranhaIdentity<IdentitySQLServerDb>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));

Hopefully, I can deploy this to Winhost and have a new shiny website in .Net Core.

Many thanks
