### ISSUE TITLE
Unable to cast object of type 'Piranha.Models.Taxonomy' to type 'System.Nullable`1[System.Guid]'.

### ISSUE THREAD

**Issue by stefanolsenn** [PiranhaCMS/piranha.core#563]
**CmsController.cs**
```
[HttpGet, Route("category")]
public async Task<IActionResult> Category(Guid blog, string slug)
{
    var category = await _api.Posts.GetCategoryBySlugAsync(blog, slug);

    if (category == null) return NotFound();

    return Ok(category);
}
```
**Values:**
```
blog = 2b0f28c7-aa54-4e45-b54d-1ec2fee18a33
slug = blogs
```
**Raw exception details:**
```
System.InvalidCastException: Unable to cast object of type 'Piranha.Models.Taxonomy' to type 'System.Nullable`1[System.Guid]'.
   at Piranha.Cache.SimpleCache.Get[T](String key)
   at Piranha.Services.PostService.GetCategoryBySlugAsync(Guid blogId, String slug)
   at DPV.Web.Controllers.CmsController.Category(Guid blog, String slug) in (...)/Controllers/CmsController.cs:line 192
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Piranha.AspNetCore.SitemapMiddleware.Invoke(HttpContext context, IApi api, IApplicationService service)
   at Piranha.AspNetCore.StartPageMiddleware.Invoke(HttpContext context, IApi api, IApplicationService service)
   at Piranha.AspNetCore.ArchiveMiddleware.Invoke(HttpContext context, IApi api, IApplicationService service)
   at Piranha.AspNetCore.PostMiddleware.Invoke(HttpContext context, IApi api, IApplicationService service)
   at Piranha.AspNetCore.PageMiddleware.Invoke(HttpContext context, IApi api, IApplicationService service)
   at Piranha.AspNetCore.AliasMiddleware.Invoke(HttpContext context, IApi api, IApplicationService service)
   at Piranha.AspNetCore.ApplicationMiddleware.Invoke(HttpContext context, IApi api, IApplicationService service)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

The first time I call it, it works as intended. The second time it throws this error.
I'm on version 6.0 right now.

**Comment by tidyui** [comment]
Hi there! This was one of the issues fixed in `6.0.1`

**Comment by stefanolsenn** [comment]
Oh cool. Thanks!

**Comment by tidyui** [comment]
And while you're at it, upgrade `Piranha.Manager` to 6.0.2 as some outdated `css` & `js` resources where deployed with the manager package.
